### ISSUE TITLE
Design/Activity diagrams are out-of-date and incomplete

### ISSUE THREAD

**Issue by twilson271828** [USGS-Astrogeology/SensorUtils#153]
This should be rectified as quickly as possible.

**Comment by jessemapel** [comment]
This has been finished.
[SensorUtils_Phase.pdf](https://github.com/USGS-Astrogeology/SensorUtils/files/2489531/SensorUtils_Phase.pdf)
[SensorUtils_SensorModelFactory.pdf](https://github.com/USGS-Astrogeology/SensorUtils/files/2489532/SensorUtils_SensorModelFactory.pdf)
[SensorUtils_API.pdf](https://github.com/USGS-Astrogeology/SensorUtils/files/2489533/SensorUtils_API.pdf)

**Comment by thareUSGS** [comment]
Nice to see these updated. One comment. For SensorUtils_Phase.pdf, all the content (pages) are there but the formatting as a PDF is a little disjointed (like a puzzle).  Not a huge thing to fix as a PDF as long as we keep the original diagram available.

**Comment by jessemapel** [comment]
@thareUSGS The pdf looks fine to me. Can you show me what's wrong with it tomorrow.
