### ISSUE TITLE
Are there any coding standards we want to follow?

### ISSUE THREAD

**Issue by ihumphrey-usgs** [USGS-Astrogeology/SensorUtils#62]
If so, could we use a c++ linter? (e.g. `cppcheck`, `cpplint`, etc.)

**Comment by jessemapel** [comment]
I vote we pick something, anything. This could be just a chance to learn how to setup the linter/linter bot.

**Comment by jlaura** [comment]
pick one and added it

**Comment by ihumphrey-usgs** [comment]
`cppcheck` -- static analysis tool
`cpplint` -- c++ style linter according to google style guide 
`KWStyle` -- configurable c++ style linter, maintained by KitWare
`Vera++` -- configurable c++ linter, last maintained in 2015
`clang-tidy` -- clang wrapper c++ linter and fixer (fixes code -- **experimental feature**)

From an easy-to-set-up perspective, `cpplint` and `KWStyle` seem like the better candidates.

I'll create a ticket to add one.

**Comment by jessemapel** [comment]
+1 for cpplint

**Comment by jessemapel** [comment]
I think this is resolved now? We're going with google style and cpplint?
