### ISSUE TITLE
Should we use latitude and longitude in radians?

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/SensorUtils#73]
If we're sticking to Radians for this library should be use latitude and longitude in radians? That seems odd to me.

**Comment by jessemapel** [comment]
No one uses radians, we should do these in degrees.

**Comment by AstroKEW78** [comment]
Agreed, degrees for lat and lon makes the most sense.

**Comment by thareUSGS** [comment]
ugh. As a "computational" library I want to stay with radians (even for Lat/Lon).  But I don't think I can stomach using radians for Lat/Lon.  Unfortunately, angles are more naturally defined in radians - and Lat/Lons are angles.

Looking at other "geo" libraries you are right - no one uses radians for Lat/Lon. Just make sure the input parameters units are well documented. Anyone else want to chime in?

**Comment by jessemapel** [comment]
@thareUSGS see #74 we do need to worry a bit about that, but I think if we just pick 1 thing and stick to it that will work better.

**Comment by thareUSGS** [comment]
👍 🌮
