### ISSUE TITLE
Handling floating point equality

### ISSUE THREAD

**Issue by AstroKEW78** [USGS-Astrogeology/SensorUtils#76]
We need to decide on how we're handling floating point equality.
For doubles, Tyler and I think it would make sense to use DBL_MIN from float.h (which is ~O(10^-305), IIRC).
Any comments?

**Comment by jessemapel** [comment]
@AstroKEW78 What's the context for comparing floating point numbers? Where do we have to do this?

**Comment by jessemapel** [comment]
is this related to computing longitude at the pole and such?

**Comment by twilson271828** [comment]
If we're working with doubles, it's going to be an issue at some point.  ISIS does not seem to have a consistent policy on how to handle it.  It varies from developer to developer.

**Comment by jessemapel** [comment]
I'm of the opinion we make a decision when it comes up. If we try and come up with something now and then no one needs it for 6 months, chances are we won't remember what we decided.

**Comment by AstroKEW78** [comment]
Well it has come up with one of my methods, where a vector length is checked against zero.

**Comment by jessemapel** [comment]
Interesting article linked from how gtest does floating point comparisons https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

**Comment by jessemapel** [comment]
I'm fine with using DBL_MIN then

**Comment by AstroKEW78** [comment]
Armadillo has a method called "approx_equal()", which I'll use. 
http://arma.sourceforge.net/docs.html#approx_equal

**Comment by jessemapel** [comment]
:+1:

**Comment by thareUSGS** [comment]
👍 I like the use of "approx_equal" since it can be feed a tolerance.
