### ISSUE TITLE
Discuss whether we should split up rec2lat and computeRADec to individual methods for each value.

### ISSUE THREAD

**Issue by jcwbacker** [USGS-Astrogeology/SensorUtils#87]
Related to twilson271525 comment in PR # 79: Should we have functions that just return RightAscension and Declination instead of returning both at the same time (which this does)?

I think that we should consider whether to split up calls of reclat and computeRADec. During Jeff Anderson's sensor model refactor, we wrote separate latitude(recCoord), longitude, radius, rightAscension, declination methods after we determined that it didn't save us to compute them together and there could be circumstances where someone wants one of these values without the need to calculate all.

See: http://subversion.wr.usgs.gov/websvn/filedetails.php?repname=ISIS+Development+Repository&path=%2Fisis3%2Fbranches%2FsensorModelRefactor%2Fisis%2Fsrc%2FsensorModel%2Fobjs%2FGeometry3D%2FGeometry3D.cpp&peg=6927

**Comment by kberryUSGS** [comment]
Agreed, especially with this part "I think that we should consider whether to split up calls of reclat and computeRADec". If we don't split them up, we should at least update the documentation for rec2lat to mention that it is valid for both computing RAs and Decs and lat/lon (if this is accurate.)

**Comment by thareUSGS** [comment]
We should have single value outputs for our converters.
