### ISSUE TITLE
Add validator method to ensure direction and position coordinate vectors are of size 3 

### ISSUE THREAD

**Issue by jcwbacker** [USGS-Astrogeology/SensorUtils#91]
In order to prevent repeated code in each method, we should pass input params through a validator method before assuming size 3.

**Comment by jessemapel** [comment]
We may want to accept 6 element state vectors also. SPICE will often return a 6 element state vector containing the position followed by the velocity.

**Comment by jessemapel** [comment]
Obsoleted by new design
